---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore, Gemfile]
permalink: / ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "Keemei: Validate tabular bioinformatics file formats in Google Sheets"
keywords:    "Keemei, tabular, bioinformatics, metadata, validation, validate, QIIME, qiime, Google Sheets, add-on, spreadsheet, file format"
description: "Keemei is an open source Google Sheets add-on for validating tabular bioinformatics file formats, including QIIME mapping files."
source_link: "https://github.com/biocore/Keemei"
favicon:     "/favicon.ico"
touch_icon:
google_analytics_key: UA-38042047-2


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#29ABE2'
  green:     '#00BF10'
  purple:    '#5F003A'
  orange:    '#FFC000'
  turquoise: '#3FFFE0'
